### ISSUE TITLE
Public Beta launch of Station

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/roadmap#4]
eta: 2023-11-03

description: Station will be made publicly available to download. There will be a marketing website accompanying the launch. Everyone can start contributing their resources to the Filecoin economy via Station. The payment system must be capable of handling tens of thousands of Station users. 

We want to do a soft-launch of Station with rewards, to do more testing before big public GA announcement.

The tasks in this milestone may include things like GTM messaging, marketing material, etc.

We will need a support person to help early adopters and make sure we answer their questions in a timely manner.

**Comment by patrickwoodhead** [comment]
Removing dependency on Saturn

**Comment by momack2** [comment]
@juliangruber - heya, I see the date for this has changed to october? That seems like a surprising and very far out milestone change. can we discuss?

**Comment by juliangruber** [comment]
@momack2 this is because we include rewards in the release criteria, and so far no module contributed has implemented rewards yet. The Station team is therefore (and for other reasons) creating the SPARK Retrieval Checker, which should be the first module with rewards. We have set out to create the roadmap for that this week, so that we can discuss in Friday's sync. Once the roadmap is finalized, we should have shared understanding and approval for this roadmap item, as a module with rewards is the only missing piece.

**Comment by juliangruber** [comment]
@momack2 if you're referring to my edit 2 weeks ago, this was just a syntactic change because starmaps requires ETAs to have day precision, hence I updated `2023-09` to `2023-10-01`. I could also have changed to `2023-09-30`, would you have preferred that? I think `2023-09` means "any time in that month", so it could also be the last day.

**Comment by momack2** [comment]
Ack - thanks for the clarification. Issue edits don’t show exactly what
changed, so no detailed preferences in that (9/30 vs 10/1).

 I was just surprised we’re considering the timeline for beta so far out.
Let’s discuss on Friday whether to push for SPARK sooner, or maybe
reconsider whether rewards should be required for “beta” milestone?

**Comment by juliangruber** [comment]
Friday doesn't work for the team scheduling wise, I've reached out via DM on the Filecoin Slack to find an alternative.
